services:
  bd:
    build:
      context: ../atividade-docker/Banco-IT_Talent/scripts/
      # image: my-sql
    container_name: bd
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

  backend:
    build:
      context: ../atividade-docker/Backend-IT_Talent/
      # image: nodejs
    container_name: backend
    depends_on:
      - bd
    ports:
      - "8080:8080"
    environment:
      APP_PORT: ${APP_PORT}
