# Use a imagem oficial do Node.js como base
FROM node:14

# Defina o diretório de trabalho dentro do container
WORKDIR /usr/src/app

# Copie os arquivos package.json e package-lock.json
COPY package*.json ./

# Instale as dependências do projeto
RUN npm install

# Copie o restante dos arquivos da aplicação
COPY . .

# Informe ao Docker que a aplicação expõe a porta 8080
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["node", "app.js"]
