services:
  bd:
    build:
      context: ../Banco-IT_Talent/scripts/
    container_name: bd
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  backend:
    build:
      context: .
    container_name: backend
    depends_on:
      - bd
    ports:
      - "8080:8080"
    environment:
      DB_HOST: bd
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: pass
      DB_NAME: ${MYSQL_DATABASE}
      APP_PORT: ${APP_PORT}
