services:
  bd:
    build:
      context: ../Banco-IT_Talent/scripts/  # onde irá pegar o dockerfile para criar a imagem.
    container_name: bd
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  backend:
    build:
      context: . # The "." indicates the dockerfile exists in the same directory as the compose file.
    container_name: backend
    depends_on:
      - bd
    ports:
      - "8080:8080"
    environment:
      DB_HOST: bd
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      APP_PORT: ${APP_PORT}
  
  frontend:
    build:
      context: ../Frontend-IT_Talent/
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"  # Porta exposta pelo Nginx no frontend
